name: Run Telegram Bot

# Manual trigger + Cron trigger
on:
  workflow_dispatch:    # Manual run
  schedule:
    # প্রতি ৫ ঘন্টা (UTC) restart
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests python-telegram-bot

      - name: Kill previous bot (if any)
        run: |
          pkill -f "python main.py" || echo "No previous process found"

      - name: Run Bot
        run: |
          nohup python main.py > bot.log 2>&1 &
          echo "Bot started successfully"
